front_end_model: Val_model_heatmap
model:
  batch_size: 1
  dense_loss:
    enable: false
    params:
      descriptor_dist: 4
      lambda_d: 800
  detection_threshold: 0.015
  detector_loss:
    loss_type: softmax
  eval_batch_size: 4
  lambda_loss: 1
  learning_rate: 0.0001
  name: SuperPointNet_gauss2
  nms: 4
  params: {}
  subpixel:
    enable: false
    patch_size: 0
  sparse_loss:
    enable: true
    params:
      dist: cos
      lamda_d: 1
      method: 2d
      num_masked_non_matches_per_match: 100
      num_matching_attempts: 600
      other_settings: train from pretrained, 2d method
  pretrained: pretrained/superPointNet_90000_checkpoint.pth.tar
